# Generated by Django 4.2.7 on 2023-11-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_states_jobs_states_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='living_expenses',
            field=models.CharField(default='$', max_length=5, verbose_name='Living expenses in $$$'),
        ),
    ]
