# Generated by Django 4.2.7 on 2023-11-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_states_living_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='taxes',
            field=models.CharField(default='https://taxfoundation.org/location/<django.db.models.fields.CharField>/', max_length=255, verbose_name='State taxes link'),
        ),
    ]
