# Generated by Django 4.2.7 on 2023-11-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_states_taxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='states',
            name='taxes',
        ),
    ]
