# Generated by Django 4.2.7 on 2023-11-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_states_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='taxes',
            field=models.CharField(max_length=255, null=True, verbose_name='State tax link'),
        ),
    ]
