# Generated by Django 4.2.7 on 2023-11-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_states_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='taxes',
            field=models.CharField(blank=True, default='https://taxfoundation.org/location/', max_length=255, verbose_name='State tax link'),
        ),
    ]
