# Generated by Django 4.2.7 on 2023-11-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_states_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='taxes',
            field=models.CharField(blank=True, default='This field will set by itself', max_length=255, verbose_name='State tax link'),
        ),
    ]
