# Generated by Django 4.2.7 on 2023-11-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_states_taxes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesForStates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photos')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.states')),
            ],
        ),
    ]
