# Generated by Django 4.2.7 on 2023-11-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_imagesforstates'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesforstates',
            name='descrpition',
            field=models.TextField(default='Some description for photo', verbose_name='State content'),
        ),
        migrations.AlterField(
            model_name='states',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Main photo'),
        ),
    ]
