# Generated by Django 4.2.7 on 2023-11-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_imagesforstates_descrpition_alter_states_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='lowest_annual_income',
            field=models.IntegerField(default=100, verbose_name='State lowest annual income'),
        ),
        migrations.AlterField(
            model_name='states',
            name='salary',
            field=models.IntegerField(default=1000, verbose_name='State average annual income'),
        ),
    ]
