# Generated by Django 4.2.7 on 2023-11-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_states_lowest_annual_income_alter_states_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesforstates',
            old_name='descrpition',
            new_name='description',
        ),
        migrations.AddField(
            model_name='imagesforstates',
            name='photo_header',
            field=models.CharField(default='Nature', max_length=255, verbose_name='Header for photo'),
        ),
        migrations.AlterField(
            model_name='states',
            name='content',
            field=models.TextField(verbose_name='State preview text'),
        ),
    ]
