# Generated by Django 4.2.7 on 2023-11-29 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_descrpition_imagesforstates_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_path', models.TextField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.states')),
            ],
        ),
    ]
