# Generated by Django 4.2.7 on 2023-11-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_states_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelformap',
            name='svg_path',
            field=models.TextField(blank=True),
        ),
    ]
